# Generated by Django 4.1.7 on 2023-03-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoSean', '0003_student_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
